service: multipart_uploads_to_amazon_s3
frameworkVersion: '3'
custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
  test:
    nodeEnv: test

  stage: # do not rename this profile
    nodeEnv: stage
  prod: # do not rename this profile
    nodeEnv: prod

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 900
  logRetentionInDays: 180
  stage: ${opt:stage}
  lambdaHashingVersion: 20201221
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${opt:stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  deploymentBucket:
    name: vod-serverless-deployment-bucket-${self:custom.${opt:stage}.nodeEnv}

functions:
  MultipartUploadsHandler:
    handler: dist/src/handlers/index.MultipartUploadsHandler
    name: multipart-uploads-sls
    role: MultipartUploadsRole
    events:
      - http:
          method: post
          path: MultipartUploads
          cors: true
resources:
  Resources:
    MultipartUploadsRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: MultipartUploadsRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                 - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: MultipartUploadsLogsPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
          - PolicyName: MultipartUploadsS3Policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:Get*
                    - s3:List*
                  Resource:
                    - arn:aws:s3:::*-testOne-*     # this arn should change based on your project
                    - arn:aws:s3:::*-testTwo-*/*   # this arn should change based on your project
